import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import NextTopLoader from "nextjs-toploader";
import Drawer from "@/components/Drawer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} xl:container w-full mx-auto min-h-screen`}
      >
        <NextTopLoader showSpinner={false} />
        <Drawer>
          <div className="w-full">{children}</div>
          <ToastContainer
            theme="dark"
            position="bottom-center"
            autoClose={3000}
          />
        </Drawer>
      </body>
    </html>
  );
}
