import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} container mx-auto min-h-screen flex`}
      >
        <NextTopLoader showSpinner={false} />
        <Sidebar />
        <div className="w-full">{children}</div>
        <ToastContainer
          theme="dark"
          position="bottom-center"
          autoClose={3000}
        />
      </body>
    </html>
  );
}
